config/routes.rb
Rails.application.routes.draw do
  resources :chord_diagrams
  devise_for :users
  resources :chords

  root 'chord_diagrams#new'

end

app/models/chord.rb
class Chord < ActiveRecord::Base
end

app/models/chord_diagram.rb
class ChordDiagram < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chord_diagrams_controller.rb
class ChordDiagramsController < ApplicationController
  before_action :set_chord_diagram, only: [:show, :edit, :update, :destroy]

  # GET /chord_diagrams
  # GET /chord_diagrams.json
  def index
    @chord_diagrams = ChordDiagram.all
  end

  # GET /chord_diagrams/1
  # GET /chord_diagrams/1.json
  def show
  end

  # GET /chord_diagrams/new
  def new
    @chord_diagram = ChordDiagram.new
    @chord_diagrams = ChordDiagram.all
  end

  # GET /chord_diagrams/1/edit
  def edit
    @chord_diagram = ChordDiagram.find(params[:id])
    puts @chord_diagram.chords


  end

  # POST /chord_diagrams
  # POST /chord_diagrams.json
  def create
    @chord_diagram = ChordDiagram.new(chord_diagram_params)

    respond_to do |format|
      if @chord_diagram.save
        format.html { redirect_to new_chord_diagram_url, notice: 'Chord Diagram was successfully created.' }
        format.json { render :show, status: :created, location: @chord_diagram }
      else
        format.html { render :new }
        format.json { render json: @chord_diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chord_diagrams/1
  # PATCH/PUT /chord_diagrams/1.json
  def update
    respond_to do |format|
      if @chord_diagram.update(chord_diagram_params)
        format.html { redirect_to new_chord_diagram_url, notice: 'Chord diagram was successfully updated.' }
        format.json { render :show, status: :ok, location: @chord_diagram }
      else
        format.html { render :edit }
        format.json { render json: @chord_diagram.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chord_diagrams/1
  # DELETE /chord_diagrams/1.json
  def destroy
    @chord_diagram.destroy
    respond_to do |format|
      format.html { redirect_to new_chord_diagram_url, notice: 'Chord diagram was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chord_diagram
      @chord_diagram = ChordDiagram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chord_diagram_params
      params.require(:chord_diagram).permit(:name, :chords)
    end
end

app/controllers/chords_controller.rb
class ChordsController < ApplicationController
  before_action :set_chord, only: [:show, :edit, :update, :destroy]

  # GET /chords
  # GET /chords.json
  def index
    @chords = Chord.all
  end

  # GET /chords/1
  # GET /chords/1.json
  def show
  end

  # GET /chords/new
  def new
    @chord = Chord.new
    @chords = Chord.all
  end

  # GET /chords/1/edit
  def edit
  end

  # POST /chords
  # POST /chords.json
  def create
    @chord = Chord.new(chord_params)

    respond_to do |format|
      if @chord.save
        format.html { redirect_to @chord, notice: 'Chord was successfully created.' }
        format.json { render :show, status: :created, location: @chord }
      else
        format.html { render :new }
        format.json { render json: @chord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chords/1
  # PATCH/PUT /chords/1.json
  def update
    respond_to do |format|
      if @chord.update(chord_params)
        format.html { redirect_to @chord, notice: 'Chord was successfully updated.' }
        format.json { render :show, status: :ok, location: @chord }
      else
        format.html { render :edit }
        format.json { render json: @chord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chords/1
  # DELETE /chords/1.json
  def destroy
    @chord.destroy
    respond_to do |format|
      format.html { redirect_to chords_url, notice: 'Chord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chord
      @chord = Chord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chord_params
      params.require(:chord).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chord_diagrams_helper.rb
module ChordDiagramsHelper
end

app/helpers/chords_helper.rb
module ChordsHelper
end

app/views/chord_diagrams/_form.html.erb
<%= form_for(@chord_diagram) do |f| %>
  <% if @chord_diagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chord_diagram.errors.count, "error") %> prohibited this chord_diagram from being saved:</h2>

      <ul>
      <% @chord_diagram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class ="">
  <div class="field chord-name-input">
    <!-- <%= f.label :name %><br> -->
    <%= f.text_field :name, required: true %>
  </div>
  <div class="field">
    <!-- <%= f.label :chords %><br> -->
    <%= f.text_field :chords, id: "selected", required: true  %>
  </div>
  <div class="actions">
    <%= f.submit class:"new-chord-form-button"  %>
  </div>
</div>
<% end %>

app/views/chord_diagrams/edit.html.erb
<div id = "main-container">
  <div class=" fretboard">
      <ul class="fret-row">
        <div class="note estring">e</div>
        <div class="note Bstring">b</div>
        <div class="note Gstring">G</div>
        <div class="note Astring">D</div>
        <div class="note Dstring">A</div>
        <div class="note EString">E</div>
      </ul>
  </div>

  <div class = "new-chord-form">
    <h2>Name Your Chord</h2>
    <%= render 'form' %>
    <button class = "clear-fretboard new-chord-form-button">Clear Fretboard</button>
  </div>
</div>

app/views/chord_diagrams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Chord Diagrams</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Chords</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chord_diagrams.each do |chord_diagram| %>
      <tr>
        <td><%= chord_diagram.name %></td>
        <td><%= chord_diagram.chords %></td>
        <!-- <td><%= link_to 'Show', chord_diagram %></td> -->
        <td><%= link_to 'Edit', edit_chord_diagram_path(chord_diagram) %></td>
        <td><%= link_to 'Destroy', chord_diagram, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chord diagram', new_chord_diagram_path %>

app/views/chord_diagrams/new.html.erb
<div id = "main-container">
  <div class=" fretboard">
      <ul class="fret-row">
        <div class="note estring">e</div>
        <div class="note Bstring">b</div>
        <div class="note Gstring">G</div>
        <div class="note Astring">D</div>
        <div class="note Dstring">A</div>
        <div class="note EString">E</div>
      </ul>
  </div>

  <div class = "new-chord-form">
    <h2>Name Your Chord</h2>
    <%= render 'form' %>
    <button class = "clear-fretboard new-chord-form-button">Clear Fretboard</button>
    <button class = "show-edit new-chord-form-button">Edit Chords </button>
  </div>

<div class = "crud-buttons">
    <% @chord_diagrams.each do |chord_diagram| %>
      <tr>
        <td class = "user-sel-chord">
        <button class="sel-button" data-chord="<%= chord_diagram.chords.gsub(/[\s']/,'')%>"><%= chord_diagram.name %>
        </button>
        <!-- <%= chord_diagram.chords %></td> -->
        <!-- <td><%= link_to 'Show', chord_diagram %></td> -->
        <div class = "toggle-edit-buttons">
          <td><%= link_to 'Edit', edit_chord_diagram_path(chord_diagram), class: "edit-chord" %></td>
          <td><%= link_to 'Destroy', chord_diagram, class: "destroy-chord", method: :delete, data: { confirm: 'Do you really want to delete this chord?' } %></td>
        </div>
      </tr>
    <% end %>
</div>

</div>

app/views/chord_diagrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chord_diagram.name %>
</p>

<p>
  <strong>Chords:</strong>
  <%= @chord_diagram.chords %>
</p>

<%= link_to 'Edit', edit_chord_diagram_path(@chord_diagram) %> |
<%= link_to 'Back', chord_diagrams_path %>

app/views/chords/_form.html.erb
<%= form_for(@chord) do |f| %>
  <% if @chord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chord.errors.count, "error") %> prohibited this chord from being saved:</h2>

      <ul>
      <% @chord.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>


  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_field :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chords/edit.html.erb
<h1>Editing Chord</h1>

<%= render 'form' %>

<%= link_to 'Show', @chord %> |
<%= link_to 'Back', chords_path %>

app/views/chords/index.html.erb
<p id="notice"><%= notice %></p>


 <table>
  <thead>
    <tr>
      <th>Chord Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<tbody>
    <% @chords.each do |chord| %>
      <tr>
        <td><%= chord.title %></td>
        <td><%= link_to 'Show', chord %></td>
        <td><%= link_to 'Edit', edit_chord_path(chord) %></td>
        <td><%= link_to 'Destroy', chord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chord', new_chord_path %>

app/views/chords/new.html.erb
<!-- <%= link_to 'Back', chords_path %> -->


<table>
 <thead>
   <tr>
     <th>Chord Name</th>
     <th> Chord Notes </th>
     <th colspan="3"></th>
   </tr>
 </thead>

<tbody>
    <% @chords.each do |chord| %>
      <tr>
        <td><%= chord.title %></td>
        <td><%= chord.notes %></td>
        <td><%= link_to 'Show', chord %></td>
        <td><%= link_to 'Edit', edit_chord_path(chord) %></td>
        <td><%= link_to 'Destroy', chord, method: :delete, data: { confirm: 'Do you really want to delete this chord?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/chords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @chord.title %>
</p>



<%= link_to 'Edit', edit_chord_path(@chord) %> |
<%= link_to 'Back', chords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learning to Shred</title>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class = "column column-12 logo">
  <h1 class = "directions"><%= image_tag("logo.jpg", :alt => "Learning to SHRED logo") %></h1>
</div>



<%= yield %>


<footer class="site-footer">
  <div id = "user-auth">
    <% if current_user %>
      <h3><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
    <% else %>
      <h3><%= link_to 'Signup', new_user_registration_path %> or </h3>

      <h3 class = "h3-disguise">'' </h3><h3><%= link_to 'Login', new_user_session_path %> to save chords to your profile!</h3>
  </div>
</footer>
<% end %>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>